package itmo.is.cw.GuitarMatchIS.models;

public enum TypeOfProduct {
   PEDALS_AND_EFFECTS, ELECTRIC_GUITAR, STUDIO_RECORDING_GEAR, KEYS_AND_MIDI, AMPLIFIER,
   DRUMMS_AND_PERCUSSION, BASS_GUITAR, ACOUSTIC_GUITAR, SOFTWARE_AND_ACCESSORIES
}