DROP TABLE IF EXISTS product_articles CASCADE;

DROP TABLE IF EXISTS product_user CASCADE;

DROP TABLE IF EXISTS musician_product CASCADE;

DROP TABLE IF EXISTS genre_user CASCADE;

DROP TABLE IF EXISTS type_of_musician_user CASCADE;

DROP TABLE IF EXISTS type_of_musician_musician CASCADE;

DROP TABLE IF EXISTS product_genre CASCADE;

DROP TABLE IF EXISTS musician_genre CASCADE;

DROP TABLE IF EXISTS user_musician_subscription CASCADE;

DROP TABLE IF EXISTS feedback CASCADE;

DROP TABLE IF EXISTS articles CASCADE;

DROP TABLE IF EXISTS product CASCADE;

DROP TABLE IF EXISTS app_user CASCADE;

DROP TABLE IF EXISTS musician CASCADE;

DROP TABLE IF EXISTS type_of_product CASCADE;

DROP TABLE IF EXISTS guitar_form CASCADE;

DROP TABLE IF EXISTS brand CASCADE;

DROP TABLE IF EXISTS genre CASCADE;

DROP TABLE IF EXISTS type_of_musician CASCADE;