INSERT INTO type_of_musician (name)
VALUES ('MUSICAL PRODUCER'), ('GUITARIST'), ('DRUMMER'), ('BASSIST'), ('SINGER'), ('RAPPER'), ('KEYBOARDIST');

INSERT INTO genre (name)
VALUES ('BLUES'), ('ROCK'), ('POP'), ('JAZZ'), ('RAP'), ('METAL'), ('CLASSICAL'), ('REGGAE'), ('ELECTRONIC'), ('HIP-HOP');

INSERT INTO brand (name)
VALUES ('FENDER'), ('GIBSON'), ('YAMAHA'), ('IBANEZ'), ('ESP'), ('PRS'), ('SQUIER'), ('MARTIN'), ('COLLINGS'), ('TAYLOR');

INSERT INTO guitar_form (name)
VALUES ('STRATOCASTER'), ('TELECASTER'), ('THINLINE'), ('LES PAUL'), ('V'), ('JAGUAR'), ('JAZZ-MASTER'), ('MOCKINGBIRD'), ('STAR'),
('MUSTANG');

INSERT INTO type_of_product (name)
VALUES ('PEDALS_AND_EFFECTS'), ('ELECTRIC_GUITAR'), ('STUDIO_RECORDING_GEAR'), ('KEYS_AND_MIDI'), ('AMPLIFIER'), ('DRUMS_AND_PERCUSSION'),
('BASS_GUITAR'), ('ACOUSTIC_GUITAR'), ('SOFTWARE_AND_ACCESSORIES');
